### ISSUE TITLE
s3 location prefix matching

### ISSUE THREAD

**Issue by jpells** [jasongi/collectfasta#3]
When using a custom storage class like the following I receive the error "FileNotFoundError: [Errno 2] No such file or directory: 'files.json'" during `collectstatic`.

```
class StaticStorage(S3ManifestStaticStorage):
    location = "static"
    manifest_name = "staticfiles.json"
```

It appears the following code is changing "staticfiles.json" to "files.json" in my project.

https://github.com/jasongi/collectfasta/blob/96add58b254a7829bbebb1ca2abac8f80c829a38/collectfasta/strategies/hashing.py#L111-L119

I am thinking a possible solution would be to first check if `self.remote_storage.location` does not end with a "/" and append a trailing slash if needed. Happy to help with the work if you agree the fix is appropriate.

And thank you for the package, I am hoping this will improve my deploy times :)

**Comment by jasongi** [comment]
Thanks for the report, seems easy to fix, will give it a go and raise a patch.

**Comment by jpells** [comment]
@jasongi I appreciate the fix here, it's bringing my times down from ~1 minute to 11-12 seconds. Thank you!
