### ISSUE TITLE
Incorrect version for django-storages

### ISSUE THREAD

**Issue by beaugunderson** [jasongi/collectfasta#5]
Looks like `collectfasta` relies on `is_seekable` from `storages.utils`, which was only added in `django-storages` in 1.13.2, whereas `setup.cfg` specifies >=1.6. It should be updated to `>=1.13.2`.

**Comment by jasongi** [comment]
Fixed in [3.2.1](https://github.com/jasongi/collectfasta/releases/tag/3.2.1) - thanks for the report.
